// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	model "github.com/ejcapetillo/optimized-rover/model"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// ImageAPI is an autogenerated mock type for the ImageAPI type
type ImageAPI struct {
	mock.Mock
}

// GetImages provides a mock function with given fields: nasaUrl
func (_m *ImageAPI) GetImages(nasaUrl string) (model.PhotoWrapper, error) {
	ret := _m.Called(nasaUrl)

	var r0 model.PhotoWrapper
	if rf, ok := ret.Get(0).(func(string) model.PhotoWrapper); ok {
		r0 = rf(nasaUrl)
	} else {
		r0 = ret.Get(0).(model.PhotoWrapper)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(nasaUrl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewImageAPI creates a new instance of ImageAPI. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewImageAPI(t testing.TB) *ImageAPI {
	mock := &ImageAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
