// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	model "github.com/ejcapetillo/optimized-rover/model"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// ImageService is an autogenerated mock type for the ImageService type
type ImageService struct {
	mock.Mock
}

// GetImages provides a mock function with given fields:
func (_m *ImageService) GetImages() ([]model.DailyPhoto, error) {
	ret := _m.Called()

	var r0 []model.DailyPhoto
	if rf, ok := ret.Get(0).(func() []model.DailyPhoto); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.DailyPhoto)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewImageService creates a new instance of ImageService. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewImageService(t testing.TB) *ImageService {
	mock := &ImageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
