// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// WeatherAPI is an autogenerated mock type for the WeatherAPI type
type WeatherAPI struct {
	mock.Mock
}

// GetMarsWeather provides a mock function with given fields: nasaUrl
func (_m *WeatherAPI) GetMarsWeather(nasaUrl string) error {
	ret := _m.Called(nasaUrl)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(nasaUrl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWeatherAPI creates a new instance of WeatherAPI. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewWeatherAPI(t testing.TB) *WeatherAPI {
	mock := &WeatherAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
